name: Fetch mandats on ffta

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

env:
  NODE_VERSION: 16.x

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Fetch data
        run: npm run dev
      - name: Push data
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --local user.email "sebastien48criquet@gmail.com"
          git config --local user.name "Sebastien Ahkrin"
          git pull
          git checkout -b update-workflows-data
          git add export/mandats.json
          git commit -m "chore: update mandats.json"
          git push origin update-workflows-data
          gh pr create --title "Update mandats.json" --body ""
          gh pr merge --auto --squash
